layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "post"

collections:
  designs:
    output: false
  work:
    output: true
    permalink: /work/:name

projects:
  sort_by: stars
  limit: 9
  exclude:
    forks: true

social_media:
  dribbble: danbovey
  linkedin: danbovey
  stackoverflow: 1255333
  twitter: danielbovey